# Generated by Django 4.2.4 on 2023-09-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchcategory',
            name='band_color',
        ),
        migrations.RemoveField(
            model_name='watchcategory',
            name='case_material',
        ),
        migrations.RemoveField(
            model_name='watchcategory',
            name='case_shape',
        ),
        migrations.RemoveField(
            model_name='watchcategory',
            name='dial_color',
        ),
        migrations.RemoveField(
            model_name='watchcategory',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='watchcategory',
            name='glass',
        ),
        migrations.RemoveField(
            model_name='watchcategory',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='watchcategory',
            name='strap_material',
        ),
        migrations.RemoveField(
            model_name='watchcategory',
            name='water_resistance',
        ),
    ]
